# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /usr/src/app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy source code
COPY . .

# Build the server
RUN npm run build

# Expose any port if needed (not strictly needed for stdio-based MCP)

# Run the server
CMD [ "node", "build/index.js" ]
